### PR TITLE
Teach change_track to accept a StationUri

### LINKED ISSUE #58: Pandora station in Mopidy playlist
I'd like to use Mopidy-AlarmClock to play a Pandora station at a certain time of day. It only understands Mopidy playlists, so I'd need to define a playlist file that references the Pandora station to play.

### PR DESCRIPTION
**Pull request by rgov**
This resolves #58 by allowing a playlist to include a `pandora:station:` URI. The next track plays automatically.

There is an outstanding issue: No track information shows up for the first track. I am not sure how to fix this.

### CODE REVIEW

**Comment by jcass77** [comment]
Could you perform a rebase on 'develop'? The commit history for this PR appears to be longer than it should be.

**Comment by jcass77** [comment]
Since I am also interested in this feature, I'd like to propose an alternative approach that skips over station URI's and triggers the existing ``next_track_available`` event to fill the tracklist with tracks for that station.

This has the advantage of ensuring that the track information is always available as soon as playback starts.

Please take a look at #60 to see if it meets your needs as well?

**Comment by rgov** [comment]
Fixed the commit history, but I'll look at #60 as probably a better way to do this.

**Comment by rgov** [comment]
I'll close this in favor of #60.

**Pull request closed without merging**
